applications:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    - EYEOS_DEVELOPMENT_MODE=false
    image: open365/eyeos-application:latest
    ports:
    - 7946/tcp
    - 7946/udp
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - rabbitmq:rabbit.service.consul
    - mongodb:mongo.service.consul
appservice:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/appservice.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    - EYEOS_DEVELOPMENT_MODE=false
    image: open365/eyeos-appservice:latest
    ports:
    - 7946/tcp
    - 7946/udp
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
    - ##DOCKER_VOLS##/docker-swarm:/root/.docker
    - ##DOCKER_VOLS##/multidocker-info:/var/service/multidocker-info
    links:
    - rabbitmq:rabbit.service.consul
    - mongodb:mongo.service.consul
appservicecleaner:
    command: /var/service/src/appcleaner.sh
    image: open365/eyeos-appservice:latest
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
authentication:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/authentication.envars
    environment:
    - EYEOS_DEVELOPMENT_MODE=false
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/eyeos-authentication:latest
    ports:
    - 7946/tcp
    - 7946/udp
    restart: always
    volumes:
    - ##RESOLV_PATH##:/open365/resolv.conf
    - /var/run/docker.sock:/var/run/docker.sock
    - ##DOCKER_VOLS##/license:/var/service/license
    links:
    - rabbitmq:rabbit.service.consul
    - mongodb:mongo.service.consul
    - ldap:ldap.service.consul
eyeosChat:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    environment:
    - EYEOS_DEVELOPMENT_MODE=false
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/eyeos-eyeos-chat:latest
    ports:
    - 7946/tcp
    - 7946/udp
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
eyeosDesktop:
    env_file:
    - ../../envars/general.envars
    - ../../envars/desktop.envars
    image: open365/eyeos-eyedesktop:latest
eyeosLogin:
    env_file:
    - ../../envars/general.envars
    - ../../envars/eyeoslogin.envars
    image: open365/eyeos-login:latest
filesCdnServer:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    - EYEOS_DEVELOPMENT_MODE=false
    image: open365/eyeos-files-cdn-server:latest
    ports:
    - 7946/tcp
    - 7946/udp
    - 0.0.0.0:8090:8090
    privileged: true
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RAW_FS_PATH##:/mnt/rawFS
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - mongodb:mongo.service.consul
    - redis:redis.service.consul
httpRelayServer:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    environment:
    - EYEOS_DEVELOPMENT_MODE=false
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/eyeos-http-relay-server:latest
    ports:
    - 7946/tcp
    - 7946/udp
    - 0.0.0.0:1080:1080
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - rabbitmq:rabbit.service.consul
httpToBus:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    environment:
    - EYEOS_DEVELOPMENT_MODE=false
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/eyeos-httptobusserver:latest
    ports:
    - 7946/tcp
    - 7946/udp
    - 0.0.0.0:8196:8196
    privileged: true
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - rabbitmq:rabbit.service.consul
    - mongodb:mongo.service.consul
jitsi:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/jitsi.envars
    image: open365/docker-jitsi:latest
    privileged: true
    restart: always
ldap:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    environment:
    - EYEOS_DEVELOPMENT_MODE=false
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    - LDAP_LOG_LEVEL=256
    - LOG_CONNECTION_MAX_RETRY=1000
    image: open365/ldap-discovery:latest
    ports:
    - 0.0.0.0:389:389
    - 7946/tcp
    - 7946/udp
    restart: always
    volumes:
    - ##DATA_PATH##/ldap:/var/lib/ldap
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
mailserver:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/mailserver.envars
    environment:
    - EYEOS_DEVELOPMENT_MODE=false
    image: open365/mailserver:latest
    ports:
    - 7946/tcp
    - 7946/udp
    - 0.0.0.0:25:25
    - 0.0.0.0:143:143
    - 0.0.0.0:587:587
    - 0.0.0.0:993:993
    privileged: true
    restart: always
    volumes:
    - ##DOCKER_VOLS##/ssl:/srv/ssl
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/resolv.conf
    - ##RAW_FS_PATH##:/mnt/rawFS
mongodb:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/mongo-discovery:latest
    ports:
    - 0.0.0.0:27017:27017
    - 7946/tcp
    - 7946/udp
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##DATA_PATH##/db:/data/db
    - ##RESOLV_PATH##:/open365/resolv.conf
mysql:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/mysql.envars
    image: open365/mysql-discovery:latest
    ports:
    - 7946/tcp
    - 7946/udp
    - 0.0.0.0:3306:3306
    privileged: true
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##DATA_PATH##/mysql:/var/lib/mysql
open365Mail:
    command: sleep infinity
    image: open365/open365-mail:latest
open365Office:
    command: sleep infinity
    image: open365/open365-office:latest
pimServer:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/pimserver.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: 'open365/pim-server:latest'
    ports:
    - 0.0.0.0:5232:5232
    - 7946/tcp
    - 7946/udp
    restart: always
    volumes:
    - ##RESOLV_PATH##:/open365/resolv.conf
    - '/mnt/data/pim:/data/collections'
    - /var/run/docker.sock:/var/run/docker.sock
presenceService:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    environment:
    - EYEOS_DEVELOPMENT_MODE=false
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/eyeos-presence-service:latest
    ports:
    - 7946/tcp
    - 7946/udp
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - rabbitmq:rabbit.service.consul
    - mongodb:mongo.service.consul
principalService:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/principalservice.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    - EYEOS_DEVELOPMENT_MODE=false
    image: open365/eyeos-principalservice:latest
    ports:
    - 7946/tcp
    - 7946/udp
    privileged: true
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RAW_FS_PATH##:/mnt/rawFS
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - rabbitmq:rabbit.service.consul
    - mongodb:mongo.service.consul
proxy:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/proxy.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    - EYEOS_DEVELOPMENT_MODE=false
    extra_hosts:
    - signup.service.consul:##docker0##
    image: open365/eyeos-proxy:latest
    ports:
    - 7946/tcp
    - 7946/udp
    - 0.0.0.0:80:80
    - 0.0.0.0:443:443
    privileged: true
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RAW_FS_PATH##:/mnt/rawFS
    - ##DOCKER_VOLS##/ssl:/etc/nginx/certificate
    - ##DOCKER_VOLS##/signup:/usr/share/nginx/html/signup
    - ##RESOLV_PATH##:/open365/resolv.conf
    volumes_from:
    - eyeosLogin
    - eyeosDesktop
    links:
    - seafileServer:seafileServer.service.consul
    - eyeosChat:chat.service.consul
    - filesCdnServer:cdn.service.consul
    - httpToBus:camel.service.consul
    - rabbitmq:rabbit.service.consul
    - mongodb:mongo.service.consul
    - websockify:websockify.service.consul
    - staticCache:cache.service.consul
    - httpRelayServer:httprelay.service.consul
    - jitsi:jitsi.service.consul
rabbitmq:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/rabbitmq.envars
    environment:
    - EYEOS_DEVELOPMENT_MODE=false
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    - DISCOVERY_HOSTS_FILE_PATH=/hosts/hosts.serf
    - RABBITMQ_AUTH_HOST=##docker0##
    image: open365/rabbitmq-discovery:latest
    ports:
    - 7946/tcp
    - 7946/udp
    - 0.0.0.0:5672:5672
    - 0.0.0.0:15672:15672
    - 0.0.0.0:61613:61613
    - 0.0.0.0:15674:15674
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
    - ##HOSTS##:/hosts/
rabbitmqAuth:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    environment:
    - EYEOS_RABBITMQ_AUTH_BACKEND_HTTP_BIND_ADDRESS=0.0.0.0
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/eyeos-rabbitmq-auth-backend-http:latest
    ports:
    - 7946/tcp
    - 7946/udp
    - 0.0.0.0:7108:7108
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - rabbitmq:rabbit.service.consul
redis:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    environment:
    - DOCKER_FIX_ISSUE_14203=true
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/redis-discovery:latest
    ports:
    - 7946/tcp
    - 7946/udp
    - 0.0.0.0:6379:6379
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
seafileServer:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/seafileServer.envars
    - ../../envars/mysql.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/docker-seafile:latest
    ports:
    - 0.0.0.0:8000:8000
    - 0.0.0.0:8080:8080
    - 0.0.0.0:8082:8082
    privileged: true
    restart: always
    volumes:
    - ##DATA_PATH##/seafileRawData:/opt/seafile/seafile-data
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - mysql:mysql.service.consul
    - authentication:authentication.service.consul
    - ldap:ldap.service.consul
staticCache:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/staticCache.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/eyeos-static-cache:latest
    ports:
    - 7946/tcp
    - 7946/udp
    - 9909:9909
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - redis:redis.service.consul
sync:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/seafileServer.envars
    - ../../envars/seafileSync.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/eyeos-sync:latest
    privileged: true
    restart: always
    volumes:
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - rabbitmq:rabbit.service.consul
    - proxy:proxy.service.consul
    - ldap:ldap.service.consul
userGuestStatusPollingService:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    - EYEOS_DEVELOPMENT_MODE=false
    image: open365/eyeos-user-guest-status-polling-service:latest
    ports:
    - 7946/tcp
    - 7946/udp
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - rabbitmq:rabbit.service.consul
    - mongodb:mongo.service.consul
websockify:
    dns:
    - 127.0.0.1
    env_file:
    - ../../envars/general.envars
    - ../../envars/websockify.envars
    environment:
    - EYEOS_RUN_SERVER_RESOLV=/open365/resolv.conf
    image: open365/eyeos-websockify:latest
    ports:
    - 7946/tcp
    - 7946/udp
    - 8100:8100
    - 8102:8102
    - 8104:8104
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ##RESOLV_PATH##:/open365/resolv.conf
    links:
    - mongodb:mongo.service.consul
    - redis:redis.service.consul